### ISSUE TITLE
Support CSV and TSV

### ISSUE THREAD

**Issue by SheetJSDev** [SheetJS/j#1]
See https://github.com/SheetJS/js-xlsx/issues/35#issuecomment-36713273

@nox0311 I agree that there should be a parser that can handle any valid Excel format, but the JS-XLSX repo should focus on OPC formats like XLSX and XLSM and XLSB.

**Comment by YueZhaoDreams** [comment]
+1

**Comment by SheetJSDev** [comment]
This is managed in the `xlsx` dependency now
