### ISSUE TITLE
Define Decimal Precision

### ISSUE THREAD

**Issue by nottinhill** [SheetJS/j#11]
I am importing an excel file. By default Excel Internally handles decimals to the 15th place or something, but display these numbers as to a precision of 2 places behind the floating point. 

When importing with J and xlsx.js it takes "what the human eye sees" out of the cells, but not the underlying values, internally held by excel. 

Is there a method to define decimal precision when importing / exporting excel files?

If not, consider this is a feature request.

**Comment by SheetJSDev** [comment]
The raw value should be stored as the `.v` field of the cell object (the displayed value is stored in the `.w` field).  Do you have an example where it's not exposed?

**Comment by nottinhill** [comment]
`workbook               = J.readFile(filename)
workbookJSON      = J.utils.to_json(workbook)
sheetArray        = []
  for k,v of workbookJSON
    sheetArray.push k
sheetone = sheetArray[0]
sheetoneJSON = workbookJSON[sheetone]
async.eachLimit sheetoneJSON, 100, ((item, innerCallback) ->
    console.log item.v #undefined
    console.log item # works, but only gives formated number of Excel`

Sorry for the long wait, but I was busy with other parts of the software, now after the first couple of releases this problem popped up again.

**Comment by SheetJSDev** [comment]
This is managed in the `xlsx` dependency now
