### ISSUE TITLE
How to default all sheets

### ISSUE THREAD

**Issue by ob7** [SheetJS/j#12]
Hi, I'm trying to convert my xlsx to csv from command line. But when I do, it only grabs first sheet.  I know I can set the sheet with -s operator, but I'd like to automate this as much as possible.  How do I grab all sheets? Not knowing what they may be called, since they are not labeled 0, 1, 2, etc... and sheet operator only works by naming sheet, i.e. j file.xlsx -s "My Sheet"

**Comment by verdolin** [comment]
@ob7 did you try the `-N` or `-l` options?

**Comment by ob7** [comment]
Yep I did get it working.  Thanks for the reply.
