### ISSUE TITLE
to_json omits empty cells

### ISSUE THREAD

**Issue by SystemParadox** [SheetJS/j#7]
Hi,

It seems that `to_json` uses undefined for empty cells. This makes it rather difficult to validate sheets with optional columns, or to ensure that there are no extra columns or extraneous data in unnamed columns.

In the same way, `get_cols` also omits any column with an empty header cell.

Could this be changed to use empty string or null?

Thanks.

**Comment by SheetJSDev** [comment]
This is managed in the `xlsx` dependency now
