### ISSUE TITLE
Make __rowNum__ non-enumerable

### ISSUE THREAD

**Issue by SystemParadox** [SheetJS/j#8]
Currently all rows returned by `to_json` have a `__rowNum__` property on their prototype. However, this property is enumerable, which causes it fail chai's deepEqual test.

If the property was non-enumerable this would make life much easier.

This affects both js-xls and js-xlsx. It does also affect CSV parsing with `j`, but did not find any `__rowNum__` references in js-harb so I expect this is to due with the shared json output.

Thanks.

**Comment by SheetJSDev** [comment]
This is managed in the `xlsx` dependency now
